image: mcr.microsoft.com/dotnet/sdk:7.0

services:
  - name: docker:dind
    command: ["--tls=false"]

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - dotnet test

release:
  stage: release
  only:
    - master
  artifacts:
    paths:
      - publish/
  script:
    - dotnet publish -c Release -o ../publish src/CrowdParlay.Users.Api/CrowdParlay.Users.Api.csproj
