image: mcr.microsoft.com/dotnet/sdk:7.0

services:
  - name: docker:dind
    command: ["--tls=false"]

stages:
  - build
  - test
  - publish

build:
  stage: build
  artifacts:
    paths:
      - publish/
  script:
    - dotnet restore
    - dotnet build --no-restore
    - dotnet publish -c Release -o ../publish src/CrowdParlay.Users.Api/CrowdParlay.Users.Api.csproj

test:
  stage: test
  only:
    - merge_requests
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - dotnet test --no-build

publish:
  stage: publish
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_USER/users:latest .
    - docker push $CI_REGISTRY_USER/users:latest
