version: '3.8'

services:
  postgres:
    container_name: postgres-13
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
      - "5555:5432"
    networks:
      - users-network

  crowdparlay-users:
    container_name: crowdparlay-users
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    build:
      context: .
    environment:
      RABBITMQ_AMQP_SERVER_URL: "amqp://$RABBITMQ_USER:$RABBITMQ_PASSWORD@rabbitmq:5672"
      POSTGRES_CONNECTION_STRING: "Host=postgres;Port=5432;Database=$POSTGRES_DB;Password=$POSTGRES_PASSWORD;User Id=$POSTGRES_USER"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    networks:
      - users-network

  rabbitmq:
    container_name: rabbitmq-3.9
    image: rabbitmq:3.9
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - users-network

networks:
  users-network:
    external: true
