name: Deploy

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rollout:
    name: Rollout to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Rollout restart
        uses: actions-hub/kubectl@master
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        with:
          args: rollout restart -n crowdparlay deployment/users
