name: Assert PR

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
    branches: [ master ]

jobs:
  check:
    name: Require SemVer label
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"
          add_comment: true
          message: |
            ⚠️ Merging this PR will trigger a new release, so it is necessary that the PR has one of the following labels:
            - `major` — incompatible API changes;
            - `minor` — backward compatible new functionality;
            - `patch` — backward compatible bug fixes.